import json
import logging
from typing import Dict, Any, Tuple
from app.core.models import LLMClient

logger = logging.getLogger("prompt_distiller.distiller")

DISTILLATION_SYSTEM_PROMPT = """
You are the Prompt Distiller Engine. Your job is to take raw, messy, rambling, or emotional human prompts (often in Russian or other languages) and convert them into a high-potency, hyper-concise English prompt for an advanced reasoning LLM.

STRICT INSTRUCTIONS:
1. Strip all conversational filler, greetings, emotional rants, and irrelevant background context.
2. Translate Cyrillic or foreign language text into dense, accurate English.
3. Extract all explicit constraints (e.g. word count, budget, tools, specific preferences).
4. Break multi-topic requests into numbered sub-tasks.
5. Return ONLY a valid JSON object matching this exact schema:

{
  "detected_language": "<Language of input, e.g. Russian>",
  "raw_input_summary": "<1-sentence summary of raw input>",
  "distilled_prompt": "<Ultra-concise high-potency English prompt>",
  "intent": "<Primary intent category>",
  "extracted_constraints": ["<constraint 1>", "<constraint 2>"],
  "estimated_raw_tokens": <integer token estimate of raw input>,
  "estimated_distilled_tokens": <integer token estimate of distilled English prompt>
}
"""

RESPONSE_TRANSLATION_SYSTEM_PROMPT = """
You are a response adapter. Take the following answer (generated by an AI model) and present it in a clean, direct, clear format in the user's target language ({target_lang}).
Maintain bullet points, step-by-step instructions, and technical clarity. Strip any AI conversational fluff.
"""

class PromptDistiller:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        distill_model_name = config.get("models", {}).get("distillation_model", "gemini/gemini-1.5-flash")
        exec_model_name = config.get("models", {}).get("execution_model", "gemini/gemini-1.5-pro")
        
        self.distiller_client = LLMClient(model_name=distill_model_name)
        self.executor_client = LLMClient(model_name=exec_model_name)

    def estimate_tokens(self, text: str) -> int:
        """
        Estimates token count considering Cyrillic script BPE overhead (~2.5 tokens/word for Russian, ~1.2 for English).
        """
        words = text.split()
        cyrillic_chars = sum(1 for c in text if '\u0400' <= c <= '\u04FF')
        if cyrillic_chars > len(text) * 0.2:
            return int(len(words) * 2.5) + 5
        return int(len(words) * 1.3) + 2

    async def process(self, raw_prompt: str, target_language: str = "ru") -> Dict[str, Any]:
        """
        Full 4-phase pipeline execution:
        Raw Input -> Distilled English Prompt -> Execution Model -> Target Language Output
        """
        raw_tokens = self.estimate_tokens(raw_prompt)
        
        # Phase 1 & 2: Distill & Extract
        distill_response_raw = await self.distiller_client.generate(
            system_prompt=DISTILLATION_SYSTEM_PROMPT,
            user_prompt=raw_prompt,
            response_format="json"
        )
        
        try:
            distillation_result = json.loads(distill_response_raw)
        except Exception:
            # Fallback if json parse fails
            distillation_result = {
                "detected_language": "Auto/Russian",
                "raw_input_summary": raw_prompt[:100],
                "distilled_prompt": raw_prompt,
                "intent": "general_query",
                "extracted_constraints": [],
                "estimated_raw_tokens": raw_tokens,
                "estimated_distilled_tokens": int(raw_tokens * 0.4)
            }

        distilled_prompt = distillation_result.get("distilled_prompt", raw_prompt)
        distilled_tokens = self.estimate_tokens(distilled_prompt)
        
        savings_percent = round(max(0.0, (1 - (distilled_tokens / max(1, raw_tokens))) * 100), 1)
        distillation_result["estimated_raw_tokens"] = raw_tokens
        distillation_result["estimated_distilled_tokens"] = distilled_tokens
        distillation_result["token_savings_percent"] = savings_percent

        # Phase 3: Execute Distilled Prompt against Reasoning LLM
        execution_system_prompt = (
            "You are a highly capable AI assistant. Answer the following distilled task cleanly, "
            "accurately, and directly without fluff."
        )
        raw_execution_response = await self.executor_client.generate(
            system_prompt=execution_system_prompt,
            user_prompt=distilled_prompt
        )

        # Phase 4: Format & Translate back to target language if requested
        if target_language.lower() in ["ru", "russian", "auto"]:
            target_lang_name = "Russian"
        else:
            target_lang_name = target_language

        final_response = await self.executor_client.generate(
            system_prompt=RESPONSE_TRANSLATION_SYSTEM_PROMPT.format(target_lang=target_lang_name),
            user_prompt=raw_execution_response
        )

        return {
            "distillation": distillation_result,
            "raw_execution_output": raw_execution_response,
            "final_response": final_response
        }
