import json
import re
import logging
from typing import Dict, Any, Optional
from app.core.models import LLMClient, MODEL_REGISTRY

logger = logging.getLogger("prompt_distiller.distiller")


def parse_llm_json(response_text: str) -> Dict[str, Any]:
    """Strip optional markdown code fences and parse JSON from LLM output."""
    text = response_text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\n?", "", text)
        text = re.sub(r"\n?```$", "", text).strip()
    return json.loads(text)


DISTILLATION_SYSTEM_PROMPT = """
You are the Prompt Distiller Engine. Your job is to take raw, messy, rambling, emotional, or STT-dictated human prompts (often in Russian, English, or mixed languages) and convert them into a high-potency, hyper-concise English prompt for an advanced reasoning LLM agent.

STRICT INSTRUCTIONS:
1. Strip all speech-to-text filler words and stutters:
   - Russian filler: "э-э", "ну", "короче", "типа", "так сказать", "в общем", "слушай"
   - English filler: "um", "uh", "you know", "like", "basically", "so yeah"
   - Spoken formatting: Convert "новая строка" / "абзац" / "new line" to clean structure.
2. Translate Cyrillic or foreign language text into dense, precise English.
3. Extract all explicit constraints (e.g. word count, budget, tools, specific preferences).
4. Break multi-topic requests into clean, numbered sub-tasks.
5. Return ONLY a valid JSON object matching this exact schema:

{
  "detected_language": "<Language of input, e.g. Russian>",
  "raw_input_summary": "<1-sentence summary of raw input>",
  "distilled_prompt": "<Ultra-concise high-potency English prompt>",
  "intent": "<Primary intent category>",
  "extracted_constraints": ["<constraint 1>", "<constraint 2>"],
  "estimated_raw_tokens": <integer token estimate of raw input>,
  "estimated_distilled_tokens": <integer token estimate of distilled English prompt>
}
"""


RESPONSE_TRANSLATION_SYSTEM_PROMPT = """
You are a response adapter. Take the following answer (generated by an AI model) and present it in a clean, direct, clear format in the user's target language ({target_lang}).
Maintain bullet points, step-by-step instructions, and technical clarity. Strip any AI conversational fluff.
"""


class PromptDistiller:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        models_cfg = config.get("models", {})
        self.default_distill_model = models_cfg.get("distillation_model", "gemini/gemini-2.0-flash")
        self.default_exec_model = models_cfg.get("execution_model", "gemini/gemini-2.0-flash")
        self.default_api_base = models_cfg.get("api_base")
        self.default_provider = models_cfg.get("provider")

    def estimate_tokens(self, text: str) -> int:
        """
        Estimates token count considering Cyrillic script BPE overhead (~2.5 tokens/word for Russian, ~1.2 for English).
        """
        words = text.split()
        cyrillic_chars = sum(1 for c in text if '\u0400' <= c <= '\u04FF')
        if cyrillic_chars > len(text) * 0.2:
            return int(len(words) * 2.5) + 5
        return int(len(words) * 1.3) + 2

    async def _run_distillation(
        self,
        raw_prompt: str,
        distiller_client: LLMClient,
    ) -> Dict[str, Any]:
        """
        Shared Phase 1 & 2 distillation logic: call the LLM, parse JSON, compute token metrics.
        Called by both process() and distill_only() to avoid duplication.
        """
        raw_tokens = self.estimate_tokens(raw_prompt)

        distill_response_raw = await distiller_client.generate(
            system_prompt=DISTILLATION_SYSTEM_PROMPT,
            user_prompt=raw_prompt,
            response_format="json"
        )

        try:
            distillation_result = parse_llm_json(distill_response_raw)
        except Exception as e:
            logger.warning(
                f"Failed to parse LLM distillation response as JSON ({e}). "
                f"Raw response: {distill_response_raw[:300]!r}. Falling back to raw prompt."
            )
            distillation_result = {
                "detected_language": "Auto/Russian",
                "raw_input_summary": raw_prompt[:100],
                "distilled_prompt": raw_prompt,
                "intent": "general_query",
                "extracted_constraints": [],
                "estimated_raw_tokens": raw_tokens,
                "estimated_distilled_tokens": int(raw_tokens * 0.4)
            }

        distilled_prompt = distillation_result.get("distilled_prompt", raw_prompt)
        distilled_tokens = self.estimate_tokens(distilled_prompt)
        savings_percent = round(max(0.0, (1 - (distilled_tokens / max(1, raw_tokens))) * 100), 1)

        distillation_result["estimated_raw_tokens"] = raw_tokens
        distillation_result["estimated_distilled_tokens"] = distilled_tokens
        distillation_result["token_savings_percent"] = savings_percent

        return distillation_result

    async def process(
        self,
        raw_prompt: str,
        target_language: str = "ru",
        distillation_model: Optional[str] = None,
        execution_model: Optional[str] = None,
        api_key: Optional[str] = None,
        provider: Optional[str] = None,
        api_base: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Full 4-phase pipeline execution:
        Raw Input -> Distilled English Prompt -> Execution Model -> Target Language Output
        """
        active_provider = provider or self.default_provider
        active_api_base = api_base or self.default_api_base

        if active_provider and active_provider in MODEL_REGISTRY:
            p_info = MODEL_REGISTRY[active_provider]
            fallback_distill = p_info.get("distillation_default", self.default_distill_model)
            fallback_exec = p_info.get("execution_default", self.default_exec_model)
        else:
            fallback_distill = self.default_distill_model
            fallback_exec = self.default_exec_model

        distill_model_name = distillation_model or fallback_distill
        exec_model_name = execution_model or fallback_exec

        distiller_client = LLMClient(
            model_name=distill_model_name,
            api_key=api_key,
            provider=active_provider,
            api_base=active_api_base
        )
        executor_client = LLMClient(
            model_name=exec_model_name,
            api_key=api_key,
            provider=active_provider,
            api_base=active_api_base
        )

        # Phase 1 & 2: Distill & Extract
        distillation_result = await self._run_distillation(raw_prompt, distiller_client)
        distilled_prompt = distillation_result.get("distilled_prompt", raw_prompt)

        # Phase 3: Execute Distilled Prompt against Reasoning LLM
        execution_system_prompt = (
            "You are a highly capable AI assistant. Answer the following distilled task cleanly, "
            "accurately, and directly without fluff."
        )
        raw_execution_response = await executor_client.generate(
            system_prompt=execution_system_prompt,
            user_prompt=distilled_prompt
        )

        # Phase 4: Format & Translate back to target language if requested
        if target_language.lower() in ["ru", "russian", "auto"]:
            target_lang_name = "Russian"
        else:
            target_lang_name = target_language

        final_response = await executor_client.generate(
            system_prompt=RESPONSE_TRANSLATION_SYSTEM_PROMPT.format(target_lang=target_lang_name),
            user_prompt=raw_execution_response
        )

        return {
            "distillation": distillation_result,
            "raw_execution_output": raw_execution_response,
            "final_response": final_response
        }

    async def distill_only(
        self,
        raw_prompt: str,
        distillation_model: Optional[str] = None,
        api_key: Optional[str] = None,
        provider: Optional[str] = None,
        api_base: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Runs ONLY the prompt distillation & noise removal phase (Phase 1 & 2).
        Returns the distilled English prompt and compression metrics.
        """
        active_provider = provider or self.default_provider
        active_api_base = api_base or self.default_api_base

        fallback_distill = self.default_distill_model
        if active_provider and active_provider in MODEL_REGISTRY:
            fallback_distill = MODEL_REGISTRY[active_provider].get("distillation_default", self.default_distill_model)

        distill_model_name = distillation_model or fallback_distill
        distiller_client = LLMClient(
            model_name=distill_model_name,
            api_key=api_key,
            provider=active_provider,
            api_base=active_api_base
        )

        return await self._run_distillation(raw_prompt, distiller_client)
